<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <UserSecretsId>agentmail-dotnet-webhook-sample</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/AgentMail.AspNetCore/AgentMail.AspNetCore.csproj" />
  </ItemGroup>
</Project>
